spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nelson?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

